### ISSUE TITLE
Failure running on test dataset and have error "subscript out of bounds"

### ISSUE THREAD

**Issue by dstyaaaaaa** [xuexinyu11/MitoTracer#1]
Dear MitoTracer Development Team，

I'm sorry to bother that I have some problems running MitoTracer on the example data you provided in Github. The details of the problem are below:
I loaded your test data and converted the data to MT_variants.detected.matrix as per the GitHub usage instructions.Then I ran the code for distance and calculated the detected.distance.Because of the large number of samples, I set the number of iterations to 1000 by referring to the advice in the instructions.

```
example.data.MT_variants = ErrorMutmatrix_detect(example.data)
example.data.MT_variants.detected = 
  example.data.MT_variants[example.data.MT_variants$detection == "detected",];
example.data.MT_variants.detected.matrix = 
  MTmutMatrix_refined(example.data.MT_variants.detected);
str(example.data.MT_variants.detected.matrix)

example.data.MT_variants.detected.distance = 
  MT.feature.distance(example.data.MT_variants.detected.matrix[1:12799,], 
                      iteration = 1000);
str(example.data.MT_variants.detected.distance)
```

The number of mutations are one-to-one.
![image](https://github.com/xuexinyu11/MitoTracer/assets/102961608/a966b5fb-c215-4b9e-be68-f087fc21568e)

Then I ran the MT.feature.selection function with the default parameters, but an error was reported:
![image](https://github.com/xuexinyu11/MitoTracer/assets/102961608/8c5b0150-c7dd-40a7-b67a-0b91de9fb350)

After that I checked detected.distance and found that it has some missing values:
```
na_in_distance <- is.na(example.data.MT_variants.detected.distance)
table(na_in_distance)
```

![image](https://github.com/xuexinyu11/MitoTracer/assets/102961608/9593b600-0109-439b-adde-0eb5e486f1dc)

I don't know the reason for these missing values, but guess that they might be related to the last error message? So I am here to seek help from your team, your answers and suggestions will provide me with valuable input to resolve this issue and the subsequent analysis process that I will carry out. Thank you very much for noticing my question and I'm looking forward to your reply!

stding
2024.01.08

**Comment by xuexinyu11** [comment]
Thank you for bringing this matter to our attention. We've addressed the issue in our R package and fixed the bug. Please download the latest version of MitoTracer for the updated solution.

**Comment by dstyaaaaaa** [comment]
OK,Thanks！
